# Generated by Django 4.2.16 on 2025-04-15 18:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fernet_fields.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banklar',
            },
        ),
        migrations.CreateModel(
            name='HududModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
            },
        ),
        migrations.CreateModel(
            name='IlovaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Ilova',
                'verbose_name_plural': 'Ilovalar',
            },
        ),
        migrations.CreateModel(
            name='JinoyatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Jinoyat',
                'verbose_name_plural': 'Jinoyatlar',
            },
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Natija holati',
                'verbose_name_plural': 'Natija holatlari',
            },
        ),
        migrations.CreateModel(
            name='TashkilotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
            },
        ),
        migrations.CreateModel(
            name='XitrModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Sodir etish usuli',
                'verbose_name_plural': 'Sodir etish usullari',
            },
        ),
        migrations.CreateModel(
            name='UserModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=250)),
                ('manzil', models.CharField(max_length=350)),
                ('tell', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('holat_mazmuni', models.TextField(blank=True)),
                ('karta_number', fernet_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Karta raqami 16 raqamdan iborat', regex='^\\d{16}$')])),
                ('zarar', models.DecimalField(decimal_places=5, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('pul_data', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bankmodel')),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hududmodel')),
                ('ilova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ilovamodel')),
                ('jinoyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jinoyatmodel')),
                ('natija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.resultmodel')),
                ('tashkilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tashkilotmodel')),
                ('xitr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.xitrmodel')),
            ],
            options={
                'verbose_name': "Ro'yxat",
                'verbose_name_plural': "Ro'yxatlar",
                'ordering': ['-id'],
            },
        ),
    ]
