# Generated by Django 4.2.16 on 2025-04-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodelinfo',
            name='files',
            field=models.FileField(blank=True, upload_to='media/Murijaatlar', verbose_name='murijat fayli PDF da'),
        ),
    ]
