# Generated by Django 4.2.16 on 2025-04-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usermodelinfo_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Kasb',
                'verbose_name_plural': 'Kasb',
            },
        ),
        migrations.AlterField(
            model_name='usermodelinfo',
            name='tashkilot',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tashkilotmodel'),
        ),
        migrations.AddField(
            model_name='usermodelinfo',
            name='jobs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.jobsmodel', verbose_name='Kasbingizni kiriting'),
        ),
    ]
