# Generated by Django 4.2.16 on 2025-04-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_categoryaj_options_alter_categoryaj_sup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AJ_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('files', models.FileField(upload_to='media/Aniqlangan-jinoyatlar-fayl/', verbose_name='murijat fayli')),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hududmodel')),
            ],
            options={
                'verbose_name': "Ro'yxat",
                'verbose_name_plural': "Ro'yxatlar",
                'ordering': ['-id'],
            },
        ),
    ]
