# Generated by Django 4.2.16 on 2025-04-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_aj_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='aj_article',
            name='category',
            field=models.ForeignKey(default='120', on_delete=django.db.models.deletion.CASCADE, to='myapp.categoryaj', verbose_name='Jinoyat turi'),
            preserve_default=False,
        ),
    ]
