# Generated by Django 4.2.16 on 2025-05-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_aj_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aj_article',
            name='data',
            field=models.DateField(),
        ),
    ]
