# Generated by Django 4.2.16 on 2025-05-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_aj_article_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aj_article',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
