# Generated by Django 4.2.16 on 2025-05-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_aj_article_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aj_article',
            options={'ordering': ['-id'], 'verbose_name': 'Aniqlangan Jinoyatlar', 'verbose_name_plural': 'Aniqlangan Jinoyatlar'},
        ),
        migrations.AlterField(
            model_name='aj_article',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='aj_article',
            name='files',
            field=models.FileField(upload_to='Aniqlangan-jinoyatlar-fayl/', verbose_name='murijat fayli'),
        ),
    ]
