# Generated by Django 4.2.16 on 2025-05-02 15:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_aj_article_options_alter_aj_article_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='modda')),
                ('sup', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='bandi')),
            ],
            options={
                'verbose_name': 'Fosh-etilgan Jinoyatlar Kategorya',
                'verbose_name_plural': 'Fosh-etilgan Jin Kategorya',
            },
        ),
        migrations.AlterModelOptions(
            name='aj_article',
            options={'verbose_name': 'Aniqlangan Jinoyatlar', 'verbose_name_plural': 'Aniqlangan Jinoyatlar'},
        ),
        migrations.CreateModel(
            name='Article_FJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('files', models.FileField(upload_to='Fosh-etilgan-Jinoyatlar-fayl/', verbose_name='murijat fayli')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categoryaj', verbose_name='Jinoyat turi')),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hududmodel')),
            ],
            options={
                'verbose_name': 'Fosh-etilgan Jinoyatlar',
                'verbose_name_plural': 'Fosh-etilgan Jinoyatlar',
            },
        ),
    ]
