# Generated by Django 4.2.16 on 2025-05-02 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_categoryfj_alter_aj_article_options_article_fj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryaj',
            options={'verbose_name': 'Aniqlangan-jinoyatlar Kategorya', 'verbose_name_plural': 'Aniqlangan-jinoyatlar Kategorya'},
        ),
        migrations.AlterModelOptions(
            name='categoryfj',
            options={'verbose_name': 'Fosh-etilgan Jinoyatlar Kategorya', 'verbose_name_plural': 'Fosh-etilgan Jinoyatlar Kategorya'},
        ),
        migrations.AlterField(
            model_name='article_fj',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categoryfj', verbose_name='Jinoyat turi'),
        ),
    ]
