# Generated by Django 5.2 on 2025-05-05 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_categoryaj_options_alter_categoryfj_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_fj',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categoryaj', verbose_name='Jinoyat turi'),
        ),
        migrations.DeleteModel(
            name='CategoryFJ',
        ),
    ]
