# Generated by Django 5.2 on 2025-05-05 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_article_fj_category_delete_categoryfj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Boshqa_tashkilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('files', models.FileField(upload_to='Fosh-etilgan-Jinoyatlar-fayl/', verbose_name='murijat fayli')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categoryaj', verbose_name='Jinoyat turi')),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hududmodel')),
            ],
            options={
                'verbose_name': 'Boshqa tashkilot Tomonidan',
                'verbose_name_plural': 'Boshqa tashkilot Tomonidan',
            },
        ),
    ]
