# Generated by Django 4.2.20 on 2025-05-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_article_boshqa_tashkilot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargibotBoshqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name="Targ'ibotchi shaxsi")),
                ('hudud', models.CharField(max_length=350, verbose_name="Targ'ibot o'tgazilgan joy")),
                ('file', models.FileField(upload_to="targ'ibot/", verbose_name="Targ'ibot fayli")),
            ],
            options={
                'verbose_name': "Boshqa tashkilot Targ'iboti",
                'verbose_name_plural': "Boshqa tashkilot Targ'iboti",
            },
        ),
        migrations.CreateModel(
            name='TargibotBulim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name="Targ'ibotchi shaxsi")),
                ('hudud', models.CharField(max_length=350, verbose_name="Targ'ibot o'tgazilgan joy")),
                ('file', models.FileField(upload_to="targ'ibot/", verbose_name="Targ'ibot fayli")),
            ],
            options={
                'verbose_name': "Bo'lim Targ'ibot",
                'verbose_name_plural': "Bo'lim Targ'ibot",
            },
        ),
    ]
